name: lint_pr
on: pull_request
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.8
      with:
        source: './src ./include'
        clangFormatVersion: 10
